import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "../styles/globals.css";
import Header from './components/main/Header'
import Copyright from './components/main/Copyright'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className='flex flex-col bg-slate-100 min-h-[100vh]'>
      <body className={inter.className}>
        <Header />
        {children}
        <Copyright />
      </body>
    </html>
  );
}

export default RootLayout;
