import React, { useEffect, useState } from 'react'
import { NextPage } from 'next'
import Head from 'next/head'
import FeaturedPost from '../components/FeaturedPost'
import Typography from '@mui/material/Typography'
import Grid from '@mui/material/Grid/Grid'
import { generalSearch, SearchByCategory, SearchByTag } from '../api'
import { IFeaturedPostProps } from '../types/post'
import { CircularProgress } from '@mui/material'


const Search: NextPage = () => {
    const [posts, setPosts] = useState<IFeaturedPostProps[] | null>(null);
    const [search, setSearch] = useState("");
    const [isLoading, setIsLoading] = useState(false);
    const [tag, setTag] = useState("")
    const [category, setCategory] = useState("")

    const handelSearch = async () => {
        setIsLoading(true)

        if (search) await generalSearch(search).then((res) => {
            setPosts(res.data.posts);
            setIsLoading(false)
        }).catch((err) => { console.log(err) })

        else if (tag) await SearchByTag(tag).then((res) => {
            setPosts(res.data.posts.Post);
            setIsLoading(false)
        }).catch((err) => { console.log(err) })

        else if (category) await SearchByCategory(category).then((res) => {
            setPosts(res.data.posts);
            setIsLoading(false)
        }).catch((err) => { console.log(err) })
    }

    useEffect(() => {
        if (typeof window !== "undefined") {
            setSearch(window.location.href.split("?search=")[1])
            setTag(window.location.href.split("?tag=")[1])
            setCategory(window.location.href.split("?category=")[1])
        }
    }, [])


    useEffect(() => {
        if (tag || search || category) handelSearch();
    }, [category, search, tag])

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="w-full min-h-[75vh] flex my-10 p-16 min-w-full justify-center items-center">
                {isLoading ? <CircularProgress /> : (
                    <Grid container spacing={4}>
                        {(posts && posts.length > 0) ? posts.map((post) => (
                            <div key={post.title} className="mb-4 w-full">
                                <FeaturedPost key={post.title} post={post} blogName={post.author.blogName} />
                            </div>
                        )) : (
                            <Typography className="mb-4 underLine" variant='h5' component='h1'> Sorry No Posts Found </Typography>
                        )}
                    </Grid>
                )}
            </div>
        </>
    )
}

export default Search;